inventory:
  controller_chain:
  - context:
    - literal: ./dockerfiles/layers/login
    args:
    - key:
      - literal: FROM
      value:
        inventory: controller_base
    - key:
      - literal: USER
      value:
      - special: USER
    - key:
      - literal: UID
      value:
      - special: UID
  - context:
    - literal: ./dockerfiles/additional_tasks/int-ssh-main_network
    args:
    - key:
      - literal: USER
      value:
      - special: USER
    - key:
      - literal: KEY_NAME
      value:
      - literal: int-ssh-main
    - key:
      - literal: KEY_DIR
      value:
        inventory: int_ssh_main_keys_path
  - context:
    - literal: ./dockerfiles/starters/sshd
    args: []
group:
  commands:
  - register:
      into:
        var: controller_tag
      group:
        commands:
        - image:
            tag:
              compute:
                inventory: controller_chain
  - if:
      not:
        group:
          commands:
          - image:
              tag:
                defined:
                  image:
                  - key:
                    - literal: image
                    var: project
                  - literal: controller
                  tag:
                  - var: controller_tag
      group:
        commands:
        - image:
            prune:
            - key:
              - literal: image
              var: project
            - literal: controller
            - key:
              - literal: tag
              special: sep
            - literal: '*'
        - image:
            merge:
              image:
              - key:
                - literal: image
                var: project
              - literal: controller
              tag:
              - var: controller_tag
              base:
                inventory: controller_base
              chain:
                inventory: controller_chain
