group:
  commands:
  - register:
      into:
        var: bounce_tag
      group:
        commands:
        - image:
            tag:
              compute:
                directories:
                - - literal: ./dockerfiles/login
                - - literal: ./dockerfiles/ssh
                buildargs:
                  inventory: bounce_buildargs
  - if:
      not:
        group:
          commands:
          - image:
              tag:
                defined:
                  image:
                  - key:
                    - literal: image
                    var: project
                  - literal: bounce
                  tag:
                  - var: bounce_tag
      group:
        commands:
        - image:
            prune:
            - key:
              - literal: image
              var: project
            - literal: bounce
            - key:
              - literal: tag
              special: sep
            - literal: '*'
        - image:
            merge:
              image:
              - key:
                - literal: image
                var: project
              - literal: bounce
              tag:
              - var: bounce_tag
              base:
                inventory: bounce_base
              chain:
              - context:
                - literal: ./dockerfiles/login
                args:
                  inventory: bounce_buildargs
              - context:
                - literal: ./dockerfiles/tmux
                args:
                - key:
                  - literal: USER
                  value:
                  - special: USER
              - context:
                - literal: ./dockerfiles/ssh
