inventory:
  bounce_chain:
  - context:
    - literal: ./dockerfiles/layers/login
    args:
    - key:
      - literal: FROM
      value:
        inventory: bounce_base
    - key:
      - literal: USER
      value:
      - special: USER
    - key:
      - literal: UID
      value:
      - special: UID
  - context:
    - literal: ./dockerfiles/layers/tmux
    args:
    - key:
      - literal: USER
      value:
      - special: USER
  - context:
    - literal: ./dockerfiles/layers/ssh
    args: []
  - context:
    - literal: ./dockerfiles/layers/ssh-keygen
    args:
    - key:
      - literal: USER
      value:
      - special: USER
    - key:
      - literal: KEY_NAME
      value:
      - var: ext_ssh_bridge_key_name
    - key:
      - literal: KEY_DIR
      value:
      - var: ssh_home
  - context:
    - literal: ./dockerfiles/layers/ssh-keygen
    args:
    - key:
      - literal: USER
      value:
      - special: USER
    - key:
      - literal: KEY_NAME
      value:
      - literal: int-ssh-main
    - key:
      - literal: KEY_DIR
      value:
        inventory: int_ssh_main_keys_path
  - context:
    - literal: ./dockerfiles/additional_tasks/bounce
    args:
    - key:
      - literal: USER
      value:
      - special: USER
    - key:
      - literal: KEY_NAME
      value:
      - literal: int-ssh-main
    - key:
      - literal: KEY_DIR
      value:
        inventory: int_ssh_main_keys_path
  - context:
    - literal: ./dockerfiles/starters/sshd
    args: []
group:
  commands:
  - register:
      into:
        var: bounce_tag
      group:
        commands:
        - image:
            tag:
              compute:
                inventory: bounce_chain
  - if:
      not:
        group:
          commands:
          - image:
              tag:
                defined:
                  image:
                  - key:
                    - literal: image
                    var: project
                  - literal: bounce
                  tag:
                  - var: bounce_tag
      group:
        commands:
        - image:
            prune:
            - key:
              - literal: image
              var: project
            - literal: bounce
            - key:
              - literal: tag
              special: sep
            - literal: '*'
        - image:
            merge:
              image:
              - key:
                - literal: image
                var: project
              - literal: bounce
              tag:
              - var: bounce_tag
              base:
                inventory: bounce_base
              chain:
                inventory: bounce_chain
